# Generated by Django 4.1.1 on 2022-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_quantiy_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_thumbnail",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.ImageField(default="media/default_image.jpeg", upload_to=""),
        ),
    ]
