# Generated by Django 4.1.1 on 2022-09-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage_is_thumbnail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image_url",
            new_name="image",
        ),
    ]
