# Generated by Django 4.1.1 on 2022-09-13 19:59

import core.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_image_url_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=core.image.image_upload_path),
        ),
    ]
